config/routes.rb
Railsgirls::Application.routes.draw do

  resources :tags

  root 'ideas#index'

  get "pages/info"
  resources :ideas do
    resources :ratings, only: [:create]
    collection do
      get 'pictures'
      get 'uncategorized'
    end
  end

  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ideas
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  validates :name,
    length: {
      minimum: 2,
      too_short: "must have at least %{count} words"
    },
    :presence => {:message => "Enter the idea"}
  validates :description, presence: true

  has_many :ratings
  belongs_to :category
  has_and_belongs_to_many :tags
  
  accepts_nested_attributes_for :tags

  default_scope :order => 'created_at DESC'
  scope :uncategorized, -> { where(category_id: nil) }

  def self.with_pictures
    where.not(:picture => nil)
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :idea
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :ideas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/pictures
  def pictures
    @ideas = Idea.with_pictures
    render action: 'index'
  end

  # GET /ideas/uncategorized
  def uncategorized
    @ideas = Idea.uncategorized
    render action: 'index'
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @rating = Rating.new
  end
  
  # GET /ideas/new
  def new
    @idea = Idea.new
    @tags = Tag.all
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    tags = Tag.find(params[:tag_ids])
    @idea.tags = tags
    
    #params[:tag_ids].each do |id|
    #  @idea.tags << Tag.find(id)
    #end 
    
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idea }
      else
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /ideas/1/edit
  def edit
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    tags = Tag.where(:id => params[:tag_ids])
    @idea.tags.destroy_all   #disassociate the already added organizers
    @idea.tags << tags 
    
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture, :remove_picture, :category_id, :tag_ids)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  # POST /ratings
  # POST /ratings.json
  def create
    @idea = Idea.find params[:idea_id]
    @rating = Rating.new(rating_params)
    @rating.idea = @idea

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idea }
      else
        format.html { render action: 'show', controller: "ideas" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:mark)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name, prompt: 'Would you choose a category?') %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <% if @idea.picture.present?%>
  <%= image_tag(@idea.picture.url(:large)) if @idea.picture.present? %>
  <p>
    <label>
      <%= f.check_box :remove_picture %>
      Remove avatar
    </label>
  </p>
  <% end %>
  <div class="field picture">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>

  <div>
    <% Tag.all.each do |t| %>
    <div>
      <%= f.label t.name %>
      <%= check_box_tag "tag_ids[]", t.id, @idea.tags.include?(t), :id => "tag_ids_#{t.id}" %>
    </div>
    <% end %>
	</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% content_for :javascript do %>
  <script type='text/javascript'>
    $(document).ready(function() {
      $('#idea_remove_picture').on('change', function(){
        if ($('#idea_remove_picture').is(':checked')) {
          $('.picture').hide();
        }else {
          $('.picture').show();
        }
      });

    });
  </script>

<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<%= link_to 'New Idea', new_idea_path, class: "btn btn-default" %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Mark</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.category.name if idea.category.present? %></td>
        <td><%= idea.description %></td>
        <td>
          <%= image_tag(idea.picture.url(:thumb)) if idea.picture.present? %>
        </td>
        <td><%= idea.ratings.average(:mark)%></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<div>
  <strong>Tags:</strong>
  <% @idea.tags.each do |t| %>
    <p>
      <%= t.name %>
    </p>
  <% end %>
</div>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture.url(:large)) if @idea.picture.present? %>
  <!--
  <%= image_tag(@idea.picture_url, :width => 300) if @idea.picture.present? %>
-->
</p>

<p>
  <strong>Mark:</strong>
  <%= @idea.ratings.average(:mark) %>
</p>
<a href="/ideas/edit">Edit</a>
<%= link_to 'Edit', edit_idea_path(@idea), :class => "btn btn-default" %> |
<%= link_to 'Back', ideas_path %>

<%= render 'ratings/rating_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <!-- <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" /> -->
  <!-- <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" /> -->
  <%= stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "bootstrap-theme", media: "all", "data-turbolinks-track" => true %>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Idea app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Categories", categories_path %></li>
        <li><%= link_to "Ideas", ideas_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
        <li><%= link_to "Ideas with pictures", pictures_ideas_path %></li>
        <li><%= link_to "Ideas uncategorized", uncategorized_ideas_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Rails Girls 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

<%= yield :javascript %>

</body>
</html>

app/views/pages/info.html.erb
<div class="jumbotron">
  <h1>5 kwietnia 2014 Rails Girls Youth Kraków</h1>
  <p class="lead">Join us!<p>
  <p>Today!<p>
</div>

app/views/ratings/_rating_form.html.erb
<%= form_for([@idea, @rating]) do |f| %>

  <div class="field">
    <%= f.label :mark %><br>
    <%= f.select :mark, [1,2,3,4,5,6] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<%= link_to 'New Tag', new_tag_path, class: "btn btn-default" %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>